# Generated by Django 4.0.6 on 2022-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('details', models.JSONField()),
            ],
            options={
                'db_table': 'pokemon',
                'managed': True,
            },
        ),
    ]
